# configure dataSource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_farming?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          lab
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
        format_sql: true

    show-sql: true
    hibernate:
      ddl-auto: update

# configure hibernate properties